paras_adapt_model:
  paras_optim:
    name: GAM
    base_optimizer:
      name: Adam
      lr: 0.00025
      beta: 0.9
      wd: 0.0
    reg_strength: 0.1
    lambda_0_flat: 0.3
    grad_gamma: 0.05
    grad_rho: 0.01
    grad_norm_rho: 0.2
    use_projection: True
  capacity: 64
  num_classes: 1000
  bn_alpha: 0.2
  temp_factor: 1
  update_frequency: 64
  update_counter: each
  confidence_threshold: 0.33
  uncertainty_threshold: 17.
  prune_ratio: 0.5
  pruning_strategy: ln_structured
  pruning_module: conv
  metric_name: max_angle_change_feature_fc
  arch: Standard_R50
  dataset: imagenet_c
  enable_robustBN: false
  loss_name: NegWeightedMutualInformation_on_marginal
  paras_loss:
    lambda_info: 0.